# 应用名称
spring:
  application:
    name: fengben-admin
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
server:
  port: 8091
  servlet:
    context-path: /charge

